### ISSUE TITLE
tmp_tweets > tmp_tweets2

### ISSUE THREAD

**Issue by digitaldutch** [arjanbytez/verkeersongelukken-twitter#1]
In line 32 zit een kleine bug tmp_tweets moet tmp_tweets2 zijn

**Comment by arjanbytez** [comment]
geen bug toch? Ik filter vanuit tmp_tweets alleen wat nodig is, schrijf dat naar tmp_tweets2 en werk daar mee verder. Of zie ik iets over het hoofd?

**Comment by digitaldutch** [comment]
De debugger bleef er op hangen bij mij. temp_tweets bestaat namelijk niet.

Want op line 26 schrijf je de tweets weg naar tmp_tweets2 ipv tmp_tweets:
tmp_tweets2 <-search_tweets(searchText, n=1000, tweet_mode='extended')

**Comment by arjanbytez** [comment]
oe dat is slordig van me, lokaal heb ik dat blijkbaar aangepast zonder een commit naar de repo te doen. Weet hoe het werkt hier maar moet m'n weg nog een beetje vinden... aangepast!
